In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns # ensure you have installed seaborn using pip install seaborn
df=pd.read_csv('C:/Users/rosey/Downloads/energydata_complete.csv')
df.describe(include='all')

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
count,19735,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,...,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000
unique,19735,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,3/16/2016 11:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,97.694958,3.801875,21.686571,40.259739,20.341219,40.420420,22.267611,39.242500,20.855335,...,19.485828,41.552401,7.412580,755.522602,79.750418,4.039752,38.330834,3.760995,24.988033,24.988033
std,NaN,102.524891,7.935988,1.606066,3.979299,2.192974,4.069813,2.006111,3.254576,2.042884,...,2.014712,4.151497,5.318464,7.399441,14.901088,2.451221,11.794719,4.195248,14.496634,14.496634
min,NaN,10.000000,0.000000,16.790000,27.023333,16.100000,20.463333,17.200000,28.766667,15.100000,...,14.890000,29.166667,-5.000000,729.300000,24.000000,0.000000,1.000000,-6.600000,0.005322,0.005322
25%,NaN,50.000000,0.000000,20.760000,37.333333,18.790000,37.900000,20.790000,36.900000,19.530000,...,18.000000,38.500000,3.670000,750.933333,70.333333,2.000000,29.000000,0.900000,12.497889,12.497889
50%,NaN,60.000000,0.000000,21.600000,39.656667,20.000000,40.500000,22.100000,38.530000,20.666667,...,19.390000,40.900000,6.920000,756.100000,83.666667,3.666667,40.000000,3.430000,24.897653,24.897653
75%,NaN,100.000000,0.000000,22.600000,43.066667,21.500000,43.260000,23.290000,41.760000,22.100000,...,20.600000,44.338095,10.400000,760.933333,91.666667,5.500000,40.000000,6.570000,37.583769,37.583769
max,NaN,1080.000000,70.000000,26.260000,63.360000,29.856667,56.026667,29.236000,50.163333,26.200000,...,24.500000,53.326667,26.100000,772.300000,100.000000,14.000000,66.000000,15.500000,49.996530,49.996530

In [4]:
df.isnull().sum()

date           0
Appliances     0
lights         0
T1             0
RH_1           0
T2             0
RH_2           0
T3             0
RH_3           0
T4             0
RH_4           0
T5             0
RH_5           0
T6             0
RH_6           0
T7             0
RH_7           0
T8             0
RH_8           0
T9             0
RH_9           0
T_out          0
Press_mm_hg    0
RH_out         0
Windspeed      0
Visibility     0
Tdewpoint      0
rv1            0
rv2            0
dtype: int64

In [5]:
df=df.drop(columns=["date","lights"])
df.head(20)

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,60,19.890000,47.596667,19.200000,44.790000,19.790000,44.730000,19.000000,45.566667,17.166667,...,17.033333,45.530000,6.60,733.500000,92.000000,7.000000,63.000000,5.30,13.275433,13.275433
1,60,19.890000,46.693333,19.200000,44.722500,19.790000,44.790000,19.000000,45.992500,17.166667,...,17.066667,45.560000,6.48,733.600000,92.000000,6.666667,59.166667,5.20,18.606195,18.606195
2,50,19.890000,46.300000,19.200000,44.626667,19.790000,44.933333,18.926667,45.890000,17.166667,...,17.000000,45.500000,6.37,733.700000,92.000000,6.333333,55.333333,5.10,28.642668,28.642668
3,50,19.890000,46.066667,19.200000,44.590000,19.790000,45.000000,18.890000,45.723333,17.166667,...,17.000000,45.400000,6.25,733.800000,92.000000,6.000000,51.500000,5.00,45.410390,45.410390
4,60,19.890000,46.333333,19.200000,44.530000,19.790000,45.000000,18.890000,45.530000,17.200000,...,17.000000,45.400000,6.13,733.900000,92.000000,5.666667,47.666667,4.90,10.084097,10.084097
5,50,19.890000,46.026667,19.200000,44.500000,19.790000,44.933333,18.890000,45.730000,17.133333,...,17.000000,45.290000,6.02,734.000000,92.000000,5.333333,43.833333,4.80,44.919484,44.919484
6,60,19.890000,45.766667,19.200000,44.500000,19.790000,44.900000,18.890000,45.790000,17.100000,...,17.000000,45.290000,5.90,734.100000,92.000000,5.000000,40.000000,4.70,47.233763,47.233763
7,60,19.856667,45.560000,19.200000,44.500000,19.730000,44.900000,18.890000,45.863333,17.100000,...,17.000000,45.290000,5.92,734.166667,91.833333,5.166667,40.000000,4.68,33.039890,33.039890
8,60,19.790000,45.597500,19.200000,44.433333,19.730000,44.790000,18.890000,45.790000,17.166667,...,17.000000,45.290000,5.93,734.233333,91.666667,5.333333,40.000000,4.67,31.455702,31.455702
9,70,19.856667,46.090000,19.230000,44.400000,19.790000,44.863333,18.890000,46.096667,17.100000,...,17.000000,45.290000,5.95,734.300000,91.500000,5.500000,40.000000,4.65,3.089314,3.089314
10,230,19.926667,45.863333,19.356667,44.400000,19.790000,44.900000,18.890000,46.430000,17.100000,...,17.000000,45.290000,5.97,734.366667,91.333333,5.666667,40.000000,4.63,10.298729,10.298729
11,580,20.066667,46.396667,19.426667,44.400000,19.790000,44.826667,19.000000,46.430000,17.100000,...,16.890000,45.290000,5.98,734.433333,91.166667,5.833333,40.000000,4.62,8.827838,8.827838
12,430,20.133333,48.000000,19.566667,44.400000,19.890000,44.900000,19.000000,46.363333,17.100000,...,16.963333,45.290000,6.00,734.500000,91.000000,6.000000,40.000000,4.60,34.351142,34.351142
13,250,20.260000,52.726667,19.730000,45.100000,19.890000,45.493333,19.000000,47.223333,17.100000,...,16.890000,45.326667,6.00,734.616667,90.500000,6.000000,40.000000,4.52,19.205186,19.205186
14,100,20.426667,55.893333,19.856667,45.833333,20.033333,47.526667,19.000000,48.696667,17.100000,...,16.890000,45.345000,6.00,734.733333,90.000000,6.000000,40.000000,4.43,38.492071,38.492071
15,100,20.566667,53.893333,20.033333,46.756667,20.100000,48.466667,19.000000,48.490000,17.150000,...,16.890000,45.326667,6.00,734.850000,89.500000,6.000000,40.000000,4.35,24.884962,24.884962
16,90,20.730000,52.660000,20.166667,47.223333,20.200000,48.530000,18.926667,48.156667,17.166667,...,16.890000,45.290000,6.00,734.966667,89.000000,6.000000,40.000000,4.27,35.880925,35.880925
17,70,20.856667,53.660000,20.200000,47.056667,20.200000,48.447500,18.890000,47.963333,17.200000,...,16.890000,45.290000,6.00,735.083333,88.500000,6.000000,40.000000,4.18,49.595305,49.595305
18,80,20.890000,51.193333,20.200000,46.330000,20.200000,48.193333,18.963333,48.630000,17.200000,...,16.890000,45.200000,6.00,735.200000,88.000000,6.000000,40.000000,4.10,19.001759,19.001759
19,140,20.890000,49.800000,20.200000,46.026667,20.166667,47.633333,19.033333,49.500000,17.593333,...,16.890000,45.200000,6.00,735.233333,87.833333,6.000000,40.000000,4.07,38.872261,38.872261

 Normalizing the dataset to a common scale
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
normalised_df = pd.DataFrame(scaler.fit_transform(df),columns=df.columns)
features_df = normalised_df.drop(columns=['Appliances'])
Appliances = normalised_df['Appliances']
normalised_df.head()

In [6]:
#Normalizing the dataset to a common scale 
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler() 
normalised_df = pd.DataFrame(scaler.fit_transform(df),columns=df.columns)
features_df = normalised_df.drop(columns=['Appliances'])
Appliances = normalised_df['Appliances'] 
normalised_df.head()

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,0.046729,0.32735,0.566187,0.225345,0.684038,0.215188,0.746066,0.351351,0.764262,0.175506,...,0.223032,0.677290,0.372990,0.097674,0.894737,0.500000,0.953846,0.538462,0.265449,0.265449
1,0.046729,0.32735,0.541326,0.225345,0.682140,0.215188,0.748871,0.351351,0.782437,0.175506,...,0.226500,0.678532,0.369132,0.100000,0.894737,0.476190,0.894872,0.533937,0.372083,0.372083
2,0.037383,0.32735,0.530502,0.225345,0.679445,0.215188,0.755569,0.344745,0.778062,0.175506,...,0.219563,0.676049,0.365595,0.102326,0.894737,0.452381,0.835897,0.529412,0.572848,0.572848
3,0.037383,0.32735,0.524080,0.225345,0.678414,0.215188,0.758685,0.341441,0.770949,0.175506,...,0.219563,0.671909,0.361736,0.104651,0.894737,0.428571,0.776923,0.524887,0.908261,0.908261
4,0.046729,0.32735,0.531419,0.225345,0.676727,0.215188,0.758685,0.341441,0.762697,0.178691,...,0.219563,0.671909,0.357878,0.106977,0.894737,0.404762,0.717949,0.520362,0.201611,0.201611

In [7]:
# split the dataset into training and testing dataset

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(features_df,Appliances, test_size=0.3, random_state=1)

In [8]:
#linear regression
from sklearn.linear_model import LinearRegression
linear_model = LinearRegression()
linear_model.fit(x_train,y_train) # fit the model to the training dataset
linear_predict = linear_model.predict(x_test) # obtains predictions
linear_model.coef_
#sns.regplot(x=y_test, y=predicted_values)

array([ 5.97135216e-03,  5.35769896e-01, -2.49818579e-01, -4.58146376e-01,
        2.93219293e-01,  9.55869012e-02,  2.73438595e-02,  2.66406304e-02,
        1.26287856e-02,  1.62875003e-02,  2.48826168e-01,  3.80483674e-02,
        1.25648404e-02, -4.75942257e-02,  8.85070706e-02, -1.56562434e-01,
       -2.04718653e-01, -3.60494178e-02, -3.29546078e-01,  4.64546182e-03,
       -7.58946558e-02,  2.79277771e-02,  1.09903400e-02,  1.19042209e-01,
       -3.55819498e-04, -3.55819498e-04])

In [9]:
#Ridge regression
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=0.4)
ridge_reg.fit(x_train, y_train)
Ridge_predict = ridge_reg.predict(x_test)
ridge_reg.coef_

array([-9.42153101e-03,  5.02304245e-01, -2.14809982e-01, -4.12683191e-01,
        2.91102098e-01,  9.44954826e-02,  2.56547165e-02,  2.47971589e-02,
        8.22902984e-03,  1.64629829e-02,  2.28883283e-01,  3.54455737e-02,
        1.20614707e-02, -4.87652821e-02,  8.75517668e-02, -1.55909543e-01,
       -2.03384347e-01, -3.77646894e-02, -2.68556324e-01,  4.38899245e-03,
       -5.25076890e-02,  2.90581255e-02,  1.07851573e-02,  8.39091374e-02,
       -3.58723278e-04, -3.58723278e-04])

In [10]:
#lasso regression
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.001)
lasso_reg.fit(x_train,y_train) 
lasso_predict=lasso_reg.predict(x_test)
lasso_reg.coef_

array([ 0.00000000e+00,  8.41001414e-03,  8.41518503e-05, -0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00,  0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00,  0.00000000e+00, -0.00000000e+00,
       -4.70618302e-02,  2.77400086e-03,  0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00])

In [11]:
# Comparing the effects of Regularization
def get_weights_df(model,feat,col_name):
    weights = pd.Series(model.coef_,feat.columns).sort_values()
    weights_df=pd.DataFrame(weights).reset_index()
    weights_df.columns=['Features', col_name]
    weights_df[col_name].round(3)
    return weights_df

linear_model_weights = get_weights_df(linear_model, x_train, 'Linear_Model_Weight')
ridge_weights_df = get_weights_df(ridge_reg, x_train, 'Ridge_Weight')
lasso_weights_df = get_weights_df(lasso_reg, x_train, 'Lasso_weight')

final_weights = pd.merge(linear_model_weights, ridge_weights_df, on='Features')
final_weights =pd.merge(final_weights, lasso_weights_df, on='Features')


final_weights

       Features  Linear_Model_Weight  Ridge_Weight  Lasso_weight
0          RH_2            -0.458146     -0.412683     -0.000000
1         T_out            -0.329546     -0.268556      0.000000
2            T2            -0.249819     -0.214810      0.000084
3            T9            -0.204719     -0.203384     -0.000000
4          RH_8            -0.156562     -0.155910     -0.000000
5        RH_out            -0.075895     -0.052508     -0.047062
6          RH_7            -0.047594     -0.048765     -0.000000
7          RH_9            -0.036049     -0.037765     -0.000000
8           rv1            -0.000356     -0.000359     -0.000000
9           rv2            -0.000356     -0.000359     -0.000000
10  Press_mm_hg             0.004645      0.004389     -0.000000
11           T1             0.005971     -0.009422      0.000000
12   Visibility             0.010990      0.010785      0.000000
13           T7             0.012565      0.012061     -0.000000
14           T5             0.012629      0.008229     -0.000000
15         RH_5             0.016288      0.016463      0.000000
16         RH_4             0.026641      0.024797      0.000000
17           T4             0.027344      0.025655      0.000000
18    Windspeed             0.027928      0.029058      0.002774
19         RH_6             0.038048      0.035446     -0.000000
20           T8             0.088507      0.087552      0.000000
21         RH_3             0.095587      0.094495      0.000000
22    Tdewpoint             0.119042      0.083909      0.000000
23           T6             0.248826      0.228883      0.000000
24           T3             0.293219      0.291102      0.000000
25         RH_1             0.535770      0.502304      0.008410

In [19]:
# Absolute Error
from sklearn.metrics import mean_absolute_error
mae_linear = mean_absolute_error(y_test, linear_predict)
mae_lasso= mean_absolute_error(y_test, lasso_predict)
mae_Ridge = mean_absolute_error(y_test, Ridge_predict)
mae_linear =round(mae_linear,3)
mae_lasso =round(mae_lasso,3)
mae_Ridge =round(mae_Ridge,3)
print("Absolute error for linear reg=", mae_linear)
print("Absolute error for lasso reg=", mae_lasso)
print("Absolute error for Ridge=", mae_Ridge)

Absolute error for linear reg= 0.05
Absolute error for lasso reg= 0.056
Absolute error for Ridge= 0.05

In [20]:
#R squared value
from sklearn.metrics import r2_score
r2_linear =r2_score(y_test,linear_predict)
r2_lasso =r2_score(y_test,lasso_predict)
r2_ridge =r2_score(y_test,Ridge_predict)
r2_linear=round(r2_linear,3)
r2_lasso=round(r2_lasso,3)
r2_ridge=round(r2_ridge,3)
print("R square value for linear reg=", r2_linear)
print("R square value for lasso reg=", r2_lasso)
print("R square value for Ridge reg=", r2_ridge)

R square value for linear reg= 0.156
R square value for lasso reg= 0.025
R square value for Ridge reg= 0.156

In [18]:
#residual sum of squares for linear regression
rss = np.sum(np.square(y_test - linear_predict))
round(rss,2)

46.1

In [15]:
#root mean squared error for linear regression
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, linear_predict))
round(rmse,3)

0.088

In [16]:
#root mean squared error for ridge regression
rmse1 = np.sqrt(mean_squared_error(y_test, Ridge_predict))
round(rmse1,3)

0.088

In [17]:
#root mean squared error for lasso regression
rmse1 = np.sqrt(mean_squared_error(y_test, lasso_predict))
round(rmse1,3)

0.095

In [21]:
#linear regression of T2 and T6
import statsmodels.api as sm

X = df["T2"]
y = df["T6"]

model = sm.OLS(y, X).fit()
predictions = model.predict(X) 

model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                     T6   R-squared (uncentered):                   0.706
Model:                            OLS   Adj. R-squared (uncentered):              0.706
Method:                 Least Squares   F-statistic:                          4.738e+04
Date:                Tue, 04 Aug 2020   Prob (F-statistic):                        0.00
Time:                        21:47:01   Log-Likelihood:                         -61334.
No. Observations:               19735   AIC:                                  1.227e+05
Df Residuals:                   19734   BIC:                                  1.227e+05
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
T2             0.4100      0.002    217.664      0.000       0.406       0.414
==============================================================================
Omnibus:                      645.213   Durbin-Watson:                   0.002
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              715.689
Skew:                           0.443   Prob(JB):                    3.89e-156
Kurtosis:                       3.293   Cond. No.                         1.00
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""